### ISSUE TITLE
Bans site one - wrong but ste 2, its ok? someone have the same?

### ISSUE THREAD

**Issue by Trice1984** [DNA-styx/SBPP-Windmill-Dashboard#60]
Hello togheter,

some one has the same issue?

Seite 1 at BANS:

![S1](https://github.com/user-attachments/assets/04018718-659f-4b9c-972f-2c2c5adbab6c)

and the correct format:

Site 2
![2](https://github.com/user-attachments/assets/c8f97795-a9ba-48a6-8034-7bf06c132569)

**Comment by DNA-styx** [comment]
Thanks for reporting.

Yes it's a known issue, normally caused by some text (comments?) in the ban details being long and forcing the width of the page.

Fix is to get the long field to wrap, but I've failed to fix it the last time, let me revisit.

**Comment by Trice1984** [comment]
But its only on first Page, i have controlled Bans, no names or reasons incorrect :/

**Comment by AntiHeld-GMX** [comment]
If you change page.banlist.php(498)
from:
    $data['reason']     = stripslashes($res->fields['ban_reason']);
to
    $data['reason']     = mb_strimwidth(stripslashes($res->fields['ban_reason']), 0, 100);
all looks fine, but the full text is missing.
We need to search how we can enable a multiline string in this moment.

**Comment by AntiHeld-GMX** [comment]
May be I found a solution:
page_bans.tpl(345) add a special style "style="text-wrap: auto;" 
may be as a separate style or only add this:
<td class="px-4" style="text-wrap: auto;">

**Comment by AntiHeld-GMX** [comment]
@DNA-styx 
> can I credit you? - if you want, but is not necessary

I tried, as mentioned, truncating, but that might result in incorrect content.

So I would prefer the change in the underlaying tpl files. 
But I'm not a Web(UI)Designer...
